### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-onlyoffice-connector#13] opened 2019-11-05 13:22 UTC
Preconditions: Have the OnlyOffice app already installed with trial license.

Steps to reproduce:

1. Log in as Admin
2. Access Administer Wiki > Content > Localization
3. Select Multilingual
4. Select a couple of popular languages under Supported Languages eg. English. French, German, Italian, Chinese
5. Save the changes
6. Create a new xwiki page
7. Save some content for each language for that page
8. From the Drawer change the language for that page
9. Select the Attachments tab
10. Observe the text/buttons for each language selected

Expected results: All text/buttons are translated in the selected language.

Actual results: The "Choose Files", "New Document", "New Spreadsheet" and "New Presentation" buttons are all in English only. Also, the text in the right side of the "Choose Files" button - "No file chosen". 

Environment: Windows 10, XWiki 9.11 Standard with Chrome 78, OnlyOffice Connector Application 1.4

![ButtonsEN - CH](https://user-images.githubusercontent.com/40691112/68210876-29778780-ffdf-11e9-8d35-ec9f18d56e6d.jpg)

![ButtonsEN - DE](https://user-images.githubusercontent.com/40691112/68210877-29778780-ffdf-11e9-840f-c354aa5c0be1.jpg)

![ButtonsEN - FR](https://user-images.githubusercontent.com/40691112/68210878-2a101e00-ffdf-11e9-81eb-6c35003fe6de.jpg)

**Comment by acotiuga** [comment] 2019-11-05 13:36
This issue is duplicate of https://github.com/xwikisas/application-onlyoffice-connector/issues/12, right?

**Comment by ane-gabriela** [comment] 2019-11-05 14:01
> This issue is duplicate of #12, right?

It appears it is. But why wasn't #12 mentioned in #4 ?

**Closed** 2019-11-05 14:04 UTC
Labels: Priority: Major, Status: Duplicate, Type: Bug

**Comment by acotiuga** [comment] 2019-11-08 10:19
> > This issue is duplicate of #12, right?
> 
> It appears it is. But why wasn't #12 mentioned in #4 ?

It was not mentioned in #4 because that was about translations in Only Office UI and not in XWiki UI.

**Comment by acotiuga** [comment] 2019-11-08 10:25
Also, `"Choose Files" button - "No file chosen".` is from XWiki Standard and not related to this extension.
